StudyRate/Controllers/MarksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyRate.Domain;
using StudyRate.Domain.Entities;

namespace StudyRate.Controllers
{
    public class MarksController : Controller
    {
        private readonly AppDBContext _context;

        public MarksController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Marks
        public async Task<IActionResult> Index()
        {
            var appDBContext = _context.Marks.Include(m => m.ControlType).Include(m => m.Student).Include(m => m.Subject);
            return View(await appDBContext.ToListAsync());
        }

        // GET: Marks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks
                .Include(m => m.ControlType)
                .Include(m => m.Student)
                .Include(m => m.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // GET: Marks/Create
        public IActionResult Create()
        {
            ViewData["ControlTypeID"] = new SelectList(_context.ControlTypes, "Id", "Name");
            ViewData["StudentID"] = new SelectList(_context.Students, "Id", "Id");
            ViewData["SubjectID"] = new SelectList(_context.Subjects, "Id", "Name");
            return View();
        }

        // POST: Marks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentID,SubjectID,ControlTypeID,Score,Semester,DateAdded,Id")] Mark mark)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mark);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ControlTypeID"] = new SelectList(_context.ControlTypes, "Id", "Name", mark.ControlTypeID);
            ViewData["StudentID"] = new SelectList(_context.Students, "Id", "Id", mark.StudentID);
            ViewData["SubjectID"] = new SelectList(_context.Subjects, "Id", "Name", mark.SubjectID);
            return View(mark);
        }

        // GET: Marks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks.FindAsync(id);
            if (mark == null)
            {
                return NotFound();
            }
            ViewData["ControlTypeID"] = new SelectList(_context.ControlTypes, "Id", "Name", mark.ControlTypeID);
            ViewData["StudentID"] = new SelectList(_context.Students, "Id", "Id", mark.StudentID);
            ViewData["SubjectID"] = new SelectList(_context.Subjects, "Id", "Name", mark.SubjectID);
            return View(mark);
        }

        // POST: Marks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StudentID,SubjectID,ControlTypeID,Score,Semester,DateAdded,Id")] Mark mark)
        {
            if (id != mark.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mark);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarkExists(mark.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ControlTypeID"] = new SelectList(_context.ControlTypes, "Id", "Name", mark.ControlTypeID);
            ViewData["StudentID"] = new SelectList(_context.Students, "Id", "Id", mark.StudentID);
            ViewData["SubjectID"] = new SelectList(_context.Subjects, "Id", "Name", mark.SubjectID);
            return View(mark);
        }

        // GET: Marks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks
                .Include(m => m.ControlType)
                .Include(m => m.Student)
                .Include(m => m.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // POST: Marks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mark = await _context.Marks.FindAsync(id);
            _context.Marks.Remove(mark);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarkExists(int id)
        {
            return _context.Marks.Any(e => e.Id == id);
        }
    }
}

StudyRate/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyRate.Domain;
using StudyRate.Domain.Entities;
using StudyRate.Service;

namespace StudyRate.Controllers
{
    public class ProfessorController : Controller
    {
        private readonly AppDBContext _context;

        public ProfessorController(AppDBContext context)
        {
            _context = context;
        }

        [HttpPost]
        public ActionResult Login(string email, string password)
        {
            var professor = _context.Professors.FirstOrDefault(x => x.Email == email && x.PasswordHash == password);
            if (professor != null)
            {
                Authorization.ProffesorId = professor.Id;
                return RedirectToAction("Cabinet", "Professor");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Cabinet()
        {
            int id = Authorization.ProffesorId;
            if (id == 0)
            {
                return NotFound();
            }

            Professor professor = _context.Professors
                .Include(c => c.Position)
                .Include(c => c.Department)
                .ThenInclude(c => c.Faculty).FirstOrDefault(x => x.Id == id);

            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        public async Task<IActionResult> Edit()
        {
            int id = Authorization.ProffesorId;
            if (id == 0)
            {
                return NotFound();
            }

            var professor = await _context.Professors.FindAsync(id);
            if (professor == null)
            {
                return NotFound();
            }

            ViewData["DepartmentID"] = new SelectList(_context.Departments, "Id", "Name", professor.DepartmentID);
            ViewData["PositionID"] = new SelectList(_context.Positions, "Id", "Name", professor.PositionID);

            return View(professor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("FirstName,MiddleName,LastName,PhoneNumber,PositionID,Email,PasswordHash,DepartmentID,Id")] Professor professor)
        {
            int id = Authorization.ProffesorId;
            if (id == 0)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(professor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessorExists(professor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentID"] = new SelectList(_context.Departments, "Id", "Name", professor.DepartmentID);
            ViewData["PositionID"] = new SelectList(_context.Positions, "Id", "Name", professor.PositionID);

            return View(professor);
        }

        public IActionResult Grades()
        {
            int id = Authorization.ProffesorId;
            if (id == 0)
            {
                return NotFound();
            }

            return View();
        }

        public IActionResult ImportGrades()
        {
            int id = Authorization.ProffesorId;
            if (id == 0)
            {
                return NotFound();
            }

            var academiPlan = _context.AcademicPlans
                .Include(x => x.Subject)
                .Include(x => x.Group)
                .Where(x => x.ProfessorID == id);
            var subjects = academiPlan.GroupBy(t => new { t.SubjectID, t.Subject.Name })
                .Select(g => new { Id = g.Key.SubjectID, g.Key.Name });
            var groups = academiPlan.GroupBy(t => new { t.GroupID, t.Group.Name })
                .Select(g => new { Id = g.Key.GroupID, g.Key.Name });
            var controlTypes = _context.ControlTypes;

            ViewData["SubjectID"] = new SelectList(subjects, "Id", "Name", subjects.FirstOrDefault().Name);
            ViewData["GroupID"] = new SelectList(groups, "Id", "Name", groups.FirstOrDefault().Name);
            ViewData["ControlTypeID"] = new SelectList(controlTypes, "Id", "Name", controlTypes.FirstOrDefault().Name);

            return View();
        }

        private bool ProfessorExists(int id)
        {
            return _context.Professors.Any(e => e.Id == id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ImportGradesGSheet(int group, int subject, int controlType, string tableID, string sheet)
        {
            AcademicPlan academicPlan = _context.AcademicPlans.FirstOrDefault(x => x.GroupID == group && x.SubjectID == subject);

            GSheets gSheets = new(_context);
            var marks = gSheets.ReadEntries(tableID, sheet, academicPlan, controlType);

            if (marks == null || marks.Count == 0)
            {
                ViewBag.Message = "Помилка при імпортуванні з Гугл таблиць! Можливо таблиця пуста.";
                var academiPlan = _context.AcademicPlans
                    .Include(x => x.Subject)
                    .Include(x => x.Group)
                    .Where(x => x.ProfessorID == Authorization.ProffesorId);
                var subjects = academiPlan.GroupBy(t => new { t.SubjectID, t.Subject.Name })
                    .Select(g => new { Id = g.Key.SubjectID, g.Key.Name });
                var groups = academiPlan.GroupBy(t => new { t.GroupID, t.Group.Name })
                    .Select(g => new { Id = g.Key.GroupID, g.Key.Name });
                var controlTypes = _context.ControlTypes;

                ViewData["SubjectID"] = new SelectList(subjects, "Id", "Name", subjects.FirstOrDefault().Name);
                ViewData["GroupID"] = new SelectList(groups, "Id", "Name", groups.FirstOrDefault().Name);
                ViewData["ControlTypeID"] = new SelectList(controlTypes, "Id", "Name", controlTypes.FirstOrDefault().Name);

                return View("./ImportGrades");
            }

            _context.AddRange(marks);
            await _context.SaveChangesAsync();

            return View("/Views/Marks/Index.cshtml", marks);
        }

        [HttpPost("status")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ImportGradesExcel(int group, int subject, int controlType, [Bind("uploadedFile")] IFormFile uploadedFile)
        {
            if (uploadedFile == null)
            {
                ViewBag.Message = "Помилка при імпортуванні з MS Excel! Файл не завантажено!";
                var academiPlan = _context.AcademicPlans
                    .Include(x => x.Subject)
                    .Include(x => x.Group)
                    .Where(x => x.ProfessorID == Authorization.ProffesorId);
                var subjects = academiPlan.GroupBy(t => new { t.SubjectID, t.Subject.Name })
                    .Select(g => new { Id = g.Key.SubjectID, g.Key.Name });
                var groups = academiPlan.GroupBy(t => new { t.GroupID, t.Group.Name })
                    .Select(g => new { Id = g.Key.GroupID, g.Key.Name });
                var controlTypes = _context.ControlTypes;

                ViewData["SubjectID"] = new SelectList(subjects, "Id", "Name", subjects.FirstOrDefault().Name);
                ViewData["GroupID"] = new SelectList(groups, "Id", "Name", groups.FirstOrDefault().Name);
                ViewData["ControlTypeID"] = new SelectList(controlTypes, "Id", "Name", controlTypes.FirstOrDefault().Name);

                return View("./ImportGrades");
            }

            AcademicPlan academicPlan = _context.AcademicPlans.FirstOrDefault(x => x.GroupID == group && x.SubjectID == subject);

            MSExcel mSExcel = new(_context);
            var marks = mSExcel.GetMarks(uploadedFile, academicPlan, controlType);

            if (marks == null || marks.Count == 0)
            {
                ViewBag.Message = "Помилка при імпортуванні з MS Excel! Можливо таблиця Excel пуста.";
                var academiPlan = _context.AcademicPlans
                    .Include(x => x.Subject)
                    .Include(x => x.Group)
                    .Where(x => x.ProfessorID == Authorization.ProffesorId);
                var subjects = academiPlan.GroupBy(t => new { t.SubjectID, t.Subject.Name })
                    .Select(g => new { Id = g.Key.SubjectID, g.Key.Name });
                var groups = academiPlan.GroupBy(t => new { t.GroupID, t.Group.Name })
                    .Select(g => new { Id = g.Key.GroupID, g.Key.Name });
                var controlTypes = _context.ControlTypes;

                ViewData["SubjectID"] = new SelectList(subjects, "Id", "Name", subjects.FirstOrDefault().Name);
                ViewData["GroupID"] = new SelectList(groups, "Id", "Name", groups.FirstOrDefault().Name);
                ViewData["ControlTypeID"] = new SelectList(controlTypes, "Id", "Name", controlTypes.FirstOrDefault().Name);

                return View("./ImportGrades");
            }

            _context.AddRange(marks);
            await _context.SaveChangesAsync();

            return View("/Views/Marks/Index.cshtml", marks);
        }
    }
}

StudyRate/Views/Professor/Cabinet.cshtml
@model Professor

@{
    ViewData["Title"] = "Кабінет викладача | StudyRate";
}

<div id="content">
    <h2><a href="#">Вітаємо, @Model.LastName @Model.FirstName @Model.MiddleName!</a></h2>
    <div class="box">
        <div class="table-responsive">
            <table class="table" style="max-width:700px;margin-top:20px">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Особисті дані</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Прізвище</th>
                        <th scope="row">@Model.LastName</th>
                    </tr>
                    <tr>
                        <th scope="row">Ім'я</th>
                        <th scope="row">@Model.FirstName</th>
                    </tr>
                    <tr>
                        <th scope="row">По-батькові</th>
                        <th scope="row">@Model.MiddleName</th>
                    </tr>
                    <tr>
                        <th scope="row">Моб.телефон</th>
                        <th scope="row">@Model.PhoneNumber</th>
                    </tr>
                    <tr>
                        <th scope="row">Посада</th>
                        <th scope="row">@Model.Position.Name</th>
                    </tr>
                    <tr>
                        <th scope="row">Кафедра</th>
                        <th scope="row">@Model.Department.Name</th>
                    </tr>
                    <tr>
                        <th scope="row">Факультет</th>
                        <th scope="row">@Model.Department.Faculty.Name</th>
                    </tr>
                    <tr>
                        <th scope="row">Ел.пошта</th>
                        <th scope="row">@Model.Email</th>
                    </tr>
                    <tr>
                        <th scope="row">Пароль</th>
                        <th scope="row">**************</th>
                    </tr>
                </tbody>
            </table>
            <a href="@Url.Action("Edit", "Professor")">Редагувати особисті дані</a>
        </div>
        <div style="display: flex;max-width:700px;margin-top:20px">
            <form onsubmit="event.preventDefault()" class="box">
                <input style="width:100%" type="submit" name="" value="Виставити оцінки" onclick="location.href='@Url.Action("Index", "Marks")'">
                <br />
                <br />
                <input style="width:100%" type="submit" name="" value="Імпортувати оцінки" onclick="location.href='@Url.Action("ImportGrades", "Professor")'">
            </form>
        </div>
    </div>
</div>

StudyRate/Views/Professor/Edit.cshtml
@model StudyRate.Domain.Entities.Professor

@{
    ViewData["Title"] = "Змінити дані | StudyRate";
}

<div id="content">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MiddleName" class="control-label"></label>
                    <input asp-for="MiddleName" class="form-control" />
                    <span asp-validation-for="MiddleName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PositionID" class="control-label"></label>
                    <select asp-for="PositionID" class="form-control" asp-items="ViewBag.PositionID"></select>
                    <span asp-validation-for="PositionID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PasswordHash" class="control-label"></label>
                    <input asp-for="PasswordHash" class="form-control" />
                    <span asp-validation-for="PasswordHash" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DepartmentID" class="control-label"></label>
                    <select asp-for="DepartmentID" class="form-control" asp-items="ViewBag.DepartmentID"></select>
                    <span asp-validation-for="DepartmentID" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <input type="submit" value="Зберегти" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

StudyRate/Views/Professor/Grades.cshtml
@model IEnumerable<StudyRate.Domain.Entities.Mark>

@{
    ViewData["Title"] = "Оцінки | StudyRate";
}
<div id="content">
    <div class="inner">
        <article class="box post post-excerpt">
            <header>
                <a asp-action="Edit">Ввести оцінку</a>
                <div class="table-responsive">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th>
                                    Студент
                                </th>
                                <th>
                                    Предмет
                                </th>
                                <th>
                                    Тип контролю
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Score)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Semester)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Student.FirstName) @Html.DisplayFor(modelItem => item.Student.LastName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Subject.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ControlType.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Score)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Semester)
                                    </td>
                                    <td>
                                        <a asp-action="EditGrade" asp-controller="Professor" asp-route-id="@item.Id">Змінити</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </header>
        </article>
    </div>
</div>

StudyRate/Views/Professor/ImportGrades.cshtml
@model StudyRate.Domain.Entities.AcademicPlan
@{
    ViewData["Title"] = "Імпорт оцінок | StudyRate";
}

<div class="blockBox1">
    <h1 style="margin-left:20px">@ViewBag.Message</h1>
    <div class="block1 block1_1">
        <h1 style="margin-left:20px">Імпортування з Google Sheets</h1>
        <div style="display: flex;">
            <section class="box text-style1">
                <div class="inner" style="font-size:20px;margin-right:20px;margin-left:20px">
                    <p>Для імпортування даних з Google Sheets:</p>
                    <ul>
                        <li>Додати наступний Email <a href="#">sheets@mystical-vial-312818.iam.gserviceaccount.com</a> в читачі таблиці з оцінками</li>
                        <li>Таблиця повинна мати два стовпня (1 - ім'я студента, 2 - оцінка)</li>
                        <li>Обрати групу і предмет</li>
                        <li>Ввести ID таблиці та назву листа у поля нижче</li>
                        <li>Натистути кнопку Імпортування</li>
                    </ul>
                </div>
            </section>
        </div>
        <div style="margin-top:20px;display:flex;justify-content:center">
            <form asp-action="ImportGradesGSheet" asp-controller="Professor" method="post" class="box">
                <select asp-for="GroupID" class="form-control" asp-items="ViewBag.GroupID" style="margin-bottom:20px" name="group"></select>
                <select asp-for="SubjectID" class="form-control" asp-items="ViewBag.SubjectID" style="margin-bottom:20px" name="subject"></select>
                <select class="form-control" asp-items="ViewBag.ControlTypeID" style="margin-bottom:20px" name="controlType"></select>
                <input style="margin-bottom:20px;width:100%" type="Text" name="tableID" placeholder="ID таблиці">
                <input style="margin-bottom:20px;width:100%" type="Text" name="sheet" placeholder="Назва листа">
                <input style="width:100%" type="submit" value="Імпортування">
            </form>
        </div>
    </div>
    <div class="block1 block1_2">
        <h1 style="margin-left:20px">Імпортування з MS Excel</h1>
        <div style="display: flex;">
            <section class="box text-style1">
                <div class="inner" style="font-size:20px;margin-right:20px;margin-left:20px">
                    <p>Для імпортування даних з MS Excel:</p>
                    <ul>
                        <li>Таблиця повинна мати два стовпня (1 - ім'я студента, 2 - оцінка)</li>
                        <li>Обрати групу і предмет</li>
                        <li>Натистути кнопку Імпортування</li>
                    </ul>
                </div>
            </section>
        </div>
        <div style="margin-top:20px;display:flex;justify-content:center">
            <form asp-action="ImportGradesExcel" asp-controller="Professor" method="post" class="box" name="excelimport"  enctype="multipart/form-data">
                <select asp-for="GroupID" class="form-control" asp-items="ViewBag.GroupID" style="margin-bottom:20px" name="group"></select>
                <select asp-for="SubjectID" class="form-control" asp-items="ViewBag.SubjectID" style="margin-bottom:20px" name="subject"></select>
                <select class="form-control" asp-items="ViewBag.ControlTypeID" style="margin-bottom:20px" name="controlType"></select>
                <input type="file" id="uploadedFile" name="uploadedFile" style="margin-bottom:20px" formenctype="multipart/form-data">
                <input type="submit" value="Імпортування">
            </form>
        </div>
    </div>
</div>