StudyRate/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using StudyRate.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudyRate.Controllers
{
    public class AdminController : Controller
    {
        private readonly AppDBContext _context;

        public AdminController(AppDBContext context)
        {
            _context = context;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string username, string password)
        {
            var admin = _context.Admins.FirstOrDefault(x => x.Username == username && x.Password_hash == password);
            if (admin != null)
            {
                Authorization.AdminId = admin.Id;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

StudyRate/Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Mvc;
using StudyRate.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudyRate.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly DataManager dataManager;

        public StatisticsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult BestStudents()
        {
            return View(dataManager.Marks.GetMarks()
                .OrderByDescending(el => el.Score));
        }
        
        public IActionResult GroupsRating()
        {
            return View(dataManager.Marks.GetMarks()
                .OrderByDescending(el => el.Score));
        }

        public IActionResult SpecialtyRating()
        {
            return View(dataManager.Marks.GetMarks()
                .OrderByDescending(el => el.Score));
        }

        public IActionResult UniversityRating()
        {
            return View(dataManager.Marks.GetMarks()
                .OrderByDescending(el => el.Score));
        }

    }
}

StudyRate/Views/Shared/ContentPartial.cshtml
@model IQueryable<Mark>

<div id="content">
    <div class="inner">
        <article class="box post post-excerpt">

            <!-- Tab content -->
            <div class="tab">
                <button class="tablinks" onclick="openCity(event, 'Москва')">Москва</button>
                <button class="tablinks" onclick="openCity(event, 'Берлин')">Берлин</button>
                <button class="tablinks" onclick="openCity(event, 'Пекин')">Пекин</button>
            </div>

            <div id="Москва" class="tabcontent">
                <h3>Москва</h3>
                <p>Москва это столица России.</p>
            </div>

            <div id="Берлин" class="tabcontent">
                <h3>Берлин</h3>
                <p>Берлин это столица Германии.</p>
            </div>

            <div id="Пекин" class="tabcontent">
                <h3>Пекин</h3>
                <p>Пекин это столица Китая.</p>
            </div>
            <header>
                @if (Model.Any())
                {
                    var Model1 = Model.GroupBy(t => new { StudentID = t.StudentID })
                                .Select(g => new { Average = g.Average(p => p.Score), Count = g.Count(), Id = g.Key.StudentID })
                                .OrderByDescending(el => el.Average);
                    int i = 0;
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">ПІБ</th>
                                <th scope="col">Факультет</th>
                                <th scope="col">Група</th>
                                <th scope="col">Курс</th>
                                <th scope="col">Рік</th>
                                <th scope="col">Оцінок</th>
                                <th scope="col">Рейтинг</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var entity in Model1)
                            {
                                var ent = Model.FirstOrDefault(x => x.StudentID == entity.Id);
                                <tr>
                                    <th scope="row">@(++i)</th>
                                    <td>@ent.Student.FirstName @ent.Student.MiddleName @ent.Student.LastName</td>
                                    <td>@ent.Student.Group.Specialty.Faculty.ShortForm</td>
                                    <td>@ent.Student.Group.Name</td>
                                    <td>@(DateTime.Now.Year - ent.Student.Group.YearOfEntering)</td>
                                    <td>@ent.Student.Group.YearOfEntering</td>
                                    <td>@Model1.FirstOrDefault(x => x.Id == ent.StudentID).Count</td>
                                    <td>@Math.Round(Model1.FirstOrDefault(x => x.Id == ent.StudentID).Average, 3)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    i = 0;
                }
                <h2><a href="#">Welcome to Striped</a></h2>
                <p>A free, fully responsive HTML5 site template by HTML5 UP</p>
            </header>
            <div class="info">
                <span class="date"><span class="month">Jul<span>y</span></span> <span class="day">14</span><span class="year">, 2014</span></span>
                <ul class="stats">
                    <li><a href="#" class="icon fa-comment">16</a></li>
                    <li><a href="#" class="icon fa-heart">32</a></li>
                    <li><a href="#" class="icon brands fa-twitter">64</a></li>
                    <li><a href="#" class="icon brands fa-facebook-f">128</a></li>
                </ul>
            </div>
            <a href="#" class="image featured"><img src="images/pic01.jpg" alt="" /></a>
            <p>
                <strong>Hello!</strong> You're looking at <strong>Striped</strong>, a fully responsive HTML5 site template designed by <a href="http://twitter.com/ajlkn">AJ</a>
                for <a href="http://html5up.net">HTML5 UP</a> It features a clean, minimalistic design, styling for all basic page elements (including blockquotes, tables and lists), a
                repositionable sidebar (left or right), and HTML5/CSS3 code designed for quick and easy customization (see code comments for details).
            </p>
            <p>
                Striped is released for free under the <a href="http://html5up.net/license">Creative Commons Attribution license</a> so feel free to use it for personal projects
                or even commercial ones &ndash; just be sure to credit <a href="http://html5up.net">HTML5 UP</a> for the design. If you like what you see here, be sure to check out
                <a href="http://html5up.net">HTML5 UP</a> for more cool designs or follow me on <a href="http://twitter.com/ajlkn">Twitter</a> for new releases and updates.
            </p>
        </article>

        <!-- Post -->
        <article class="box post post-excerpt">
            <header>
                <h2><a href="#">Lorem ipsum dolor sit amet</a></h2>
                <p>Feugiat interdum sed commodo ipsum consequat dolor nullam metus</p>
            </header>
            <div class="info">
                <span class="date"><span class="month">Jul<span>y</span></span> <span class="day">8</span><span class="year">, 2014</span></span>
                <ul class="stats">
                    <li><a href="#" class="icon fa-comment">16</a></li>
                    <li><a href="#" class="icon fa-heart">32</a></li>
                    <li><a href="#" class="icon brands fa-twitter">64</a></li>
                    <li><a href="#" class="icon brands fa-facebook-f">128</a></li>
                </ul>
            </div>
            <a href="#" class="image featured"><img src="images/pic02.jpg" alt="" /></a>
            <p>
                Quisque vel sapien sit amet tellus elementum ultricies. Nunc vel orci turpis. Donec id malesuada metus.
                Nunc nulla velit, fermentum quis interdum quis, tate etiam commodo lorem ipsum dolor sit amet dolore.
                Quisque vel sapien sit amet tellus elementum ultricies. Nunc vel orci turpis. Donec id malesuada metus.
                Nunc nulla velit, fermentum quis interdum quis, convallis eu sapien. Integer sed ipsum ante.
            </p>
        </article>

        <!-- Pagination -->
        <div class="pagination">
            <!--<a href="#" class="button previous">Previous Page</a>-->
            <div class="pages">
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <span>&hellip;</span>
                <a href="#">20</a>
            </div>
            <a href="#" class="button next">Next Page</a>
        </div>

    </div>
</div>

StudyRate/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

StudyRate/Views/Shared/MetatagsPartial.cshtml
@using StudyRate.Service 
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Description != null)
{
    <meta name="keywords" content="@ViewBag.KeyWords" />
}

StudyRate/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

StudyRate/Views/Shared/SidebarPartial.cshtml
    <!-- Sidebar -->
<div id="sidebar">

    <h1 id="logo" onclick="openStat(event, 'Home', this)"><a href="@Url.Action("Index", "Home")">Study Rate</a></h1>
    <nav id="nav">
        <ul>
            <li id="myque1" onclick="openStat(event, 'Найкращі студенти', this)"><a href="@Url.Action("BestStudents", "Statistics")">Найкращі студенти</a></li>
            <li id="myque2" onclick="openStat(event, 'Рейтинг груп', this)"><a href="@Url.Action("GroupsRating", "Statistics")">Рейтинг груп</a></li>
            <li id="myque3" onclick="openStat(event, 'Кількість студентів', this)"><a href="@Url.Action("SpecialtyRating", "Statistics")">Рейтинг спеціальностей</a></li>
            <li id="myque4" onclick="openStat(event, 'Успішність університету', this)"><a href="@Url.Action("UniversityRating", "Statistics")">Рейтинг факультетів</a></li>
        </ul>
    </nav>
    @if (Authorization.StudentId == 0 && Authorization.ProffesorId == 0 && Authorization.AdminId == 0)
    {
        <section class="box text-style1">
            <div class="inner">
                <form asp-action="Login" asp-controller="Student" method="post" class="box">
                    <p class="text-muted" style="text-align:center;font-size:16px">Увійти як студент!</p>
                    <input style="margin-bottom:20px;width:100%;color:black;" type="text" name="index" id="index" placeholder="Ідентиф. код">
                    <input style="width:100%" type="submit" name="" value="Увійти">
                </form>
            </div>
        </section>
        <section class="box text-style1">
            <div class="inner">
                <form asp-action="Login" asp-controller="Professor" method="post" class="box">
                    <p style="text-align:center;font-size:16px" class="text-muted">Увійти як викладач!</p>
                    <input style="margin-bottom:20px;width:100%;color:black;" type="email" name="email" placeholder="Email">
                    <input style="margin-bottom:20px;width:100%;color:black;" type="password" name="password" id="password" placeholder="Password">
                    <input style="width:100%" type="submit" name="" value="Увійти">
                </form>
            </div>
        </section>
    }
    @if (Authorization.StudentId != 0)
    {
        <section class="box text-style1">
            <div class="inner">
                <form onsubmit="event.preventDefault()" class="box">
                    <input style="width:100%" type="submit" name="" value="Кабінет" onclick="location.href='@Url.Action("Cabinet", "Student")'">
                    <input style="width:100%;margin-top:20px" type="button" value="Вийти" onclick="location.href='@Url.Action("Index", "Home", new { i = -1 }, null)'">
                </form>
            </div>
        </section>
    }
    @if (Authorization.ProffesorId != 0)
    {
        <section class="box text-style1">
            <div class="inner">
                <form onsubmit="event.preventDefault()" class="box">
                    <input style="width:100%" type="submit" name="" value="Кабінет" onclick="location.href='@Url.Action("Cabinet", "Professor")'">
                    <input style="width:100%;margin-top:20px" type="button" value="Вийти" onclick="location.href='@Url.Action("Index", "Home", new { i = -1 }, null)'">
                </form>
            </div>
        </section>
    }
    @if (Authorization.AdminId != 0)
    {
        <section class="box text-style1">
            <div class="inner">
                <form onsubmit="event.preventDefault()" class="box">
                    <input style="width:100%" type="submit" name="" value="Кабінет" onclick="location.href='@Url.Action("Index", "Admin")'">
                    <input style="width:100%;margin-top:20px" type="button" value="Вийти" onclick="location.href='@Url.Action("Index", "Home", new { i = -1 }, null)'">
                </form>
            </div>
        </section>
    }

    <section class="box text-style1">
        <div class="inner">
            <p>
                <strong>Study Rate:</strong> Електронний журнал, який дозволяє вести облік
                успішності студентів університету.
                <br />Прико
                Designed by <a href="https://t.me/rockiee">Oleksandr Ivashchenko</a>
            </p>
        </div>
    </section>

    <ul id="copyright">
        <li>&copy; <a href="https://t.me/rockiee">Oleksandr Ivashchenko</a></li>
        <li><a href="https://t.me/rockiee">2021</a></li>
    </ul>

</div>

StudyRate/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body class="is-preload">
    @RenderBody()
    @*@await Html.PartialAsync("ContentPartial")*@
    @await Html.PartialAsync("SidebarPartial")

</body>
@await Html.PartialAsync("ScriptsPartial")
</html>